controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# app_test:
#     path: /test
#     controller: App\Controller\TestController::index 

app_cgv:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/cgv.html.twig'

app_contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/contact.html.twig'
    
app_devenirBlogueur:
    path: /devenirBlogueur
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/devenirBlogueur.html.twig'

app_joinTeam:
    path: /joinTeam
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/joinTeam.html.twig'

app_quiSommesNous:
    path: /quiSommesNous
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/quiSommesNous.html.twig'

app_values:
    path: /values
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/values.html.twig'